// Generated by scripts/recovery/generate-shims.mjs — a compat shim: no logic, only the owner's exports under the old names.
import { createProgress, renderWith } from "obix-core-component";
export { createProgress } from "obix-core-component";
export type { ProgressConfig, ProgressState } from "obix-core-component";
export const renderProgress = renderWith(createProgress);
